version: '3.8'
services:
  web:
    build:
      context: "docker/contact-service-api"
    ports:
      - "3001:3001"
    environment:
      - MONGO_DB_URL="localhost:27018"
      - DWC_API_KEY="dwc-api-key"
    depends_on:
      - db
  db:
    image: "mongo"
    ports:
      - "27018:27017"
